# Multi-Label Classification
### Random Forest Classifier

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split

import sklearn
from sklearn import metrics, model_selection, tree
from sklearn.preprocessing import MinMaxScaler

#### Carga de data sets
https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html
https://www.analyticsvidhya.com/blog/2017/08/introduction-to-multi-label-classification/

In [2]:
# Train data
X_train = pd.read_csv('x_train_smote_undersample.csv').to_numpy()
y_train = pd.read_csv('y_train_smote_undersample.csv')
y_train = y_train['LABEL']

# Test data
X_test = pd.read_csv('x_test_smote_undersample.csv').to_numpy()
y_test = pd.read_csv('y_test_smote_undersample.csv')
y_test = y_test['LABEL']

# Validation data
X_validation = pd.read_csv('x_validation_smote_undersample.csv').to_numpy()
y_validation = pd.read_csv('y_validation_smote_undersample.csv')
y_validation = y_validation['LABEL']

In [3]:
from sklearn.ensemble import RandomForestClassifier

In [4]:
clf = RandomForestClassifier(max_depth=3, random_state=6, n_jobs=10, n_estimators=100)

In [5]:
clf.fit(X_train, y_train)

RandomForestClassifier(max_depth=3, n_jobs=10, random_state=6)

In [6]:
predictions = clf.predict(X_test)

In [7]:
clf.score(X_test, y_test)

0.9889548994747328

In [8]:
print(metrics.accuracy_score(y_test, predictions))
print('Matriz de confusion Random Forest Classifier\n', metrics.confusion_matrix(y_test, predictions))
print(metrics.classification_report(y_test, predictions, target_names=['0', '1', '2', '3']))

0.9889548994747328
Matriz de confusion Random Forest Classifier
 [[293060   1507   2051     11]
 [   107 112712      0      0]
 [     1      0 103439      0]
 [     0      0   2421  36791]]
              precision    recall  f1-score   support

           0       1.00      0.99      0.99    296629
           1       0.99      1.00      0.99    112819
           2       0.96      1.00      0.98    103440
           3       1.00      0.94      0.97     39212

    accuracy                           0.99    552100
   macro avg       0.99      0.98      0.98    552100
weighted avg       0.99      0.99      0.99    552100



In [9]:
#metrics.plot_roc_curve(clf, X_test, y_test)
#plt.show()

In [10]:
import joblib

In [11]:
joblib.dump(clf, 'modelo2.h5')

['modelo2.h5']